apiVersion: apps/v1
kind: Deployment
metadata:
  name: lifebit-app
spec:
  selector:
    matchLabels:
      app: lifebit-app
  replicas: 2
  template:
    metadata:
      name: lifebit-app
      labels:
        app: lifebit-app
    spec:
      containers:
      - name: lifebit-app
        image: jakhibi/lifebit-app
        ports:
        - containerPort: 3000